name: instagram
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  crypto: ^3.0.6
  shared_preferences: ^2.5.3
  bloc: ^9.0.0
  dartz: ^0.10.1
  dots_indicator: ^4.0.1
  modal_progress_hud_nsn: ^0.5.1
  flutter_bloc: ^9.1.1
  cloud_firestore: ^5.6.12
  supabase_flutter: ^2.9.1
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  cached_network_image: ^3.4.1
  firebase_storage: ^12.4.10
  mime: ^2.0.0
  top_snackbar_flutter: ^3.3.0
  flutter_svg: ^2.2.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/images/appIcon.png"

flutter_native_splash:
  color: "#9E9E9E"
  fullscreen: true
  android: true
  ios: true

flutter:
  uses-material-design: true
